services:
  efortech-energy-monitoring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: efortech-energy-monitoring
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - grafana
    restart: unless-stopped

  grafana:
    build:
      context: ./grafana-custom
      dockerfile: Dockerfile
    container_name: grafana
    environment:
      GF_SERVER_HTTP_ADDR: 0.0.0.0
      GF_SERVER_ROOT_URL: http://192.168.1.101:4000/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_AUTH_BASIC_ENABLED: "true"
      GF_AUTH_PROXY_ENABLED: "true"
      GF_AUTH_PROXY_HEADER_NAME: X-WEBAUTH-USER
      GF_AUTH_PROXY_HEADER_PROPERTY: username
      GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
      GF_AUTH_PROXY_SYNC_TTL: "15"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_LOG_LEVEL: warn
    expose:
      - "3000"
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
